#+ARCHIVE: ~/.eig2/eig-agenda-archives.org::

Vous pouvez vous abonner à cet agenda public [[https://cloud.eig-forever.org/index.php/apps/calendar/p/5S4DP594PDIVTARU/EIG2018][en ligne]].

* Clinique hebdomadaire sur slack
  SCHEDULED: <2018-02-12 lun. 11:30-12:30 +1w>
  :PROPERTIES:
  :ID:       9695425a-0c77-49b3-be3f-59aadffca168
  :END:
* Stand up hebdomadaire sur slack
  SCHEDULED: <2018-02-16 ven. 11:30-12:30 +1w>
  :PROPERTIES:
  :ID:       66046c0c-ce90-4ceb-ab33-612cb7f622e9
  :END:
* Semaine de Bootcamp
  :PROPERTIES:
  :ID:       7d22214b-0655-4401-a130-b381c9d55dc9
  :END:

** Bootcamp - Lundi 5 février (à la DINSIC)
   :PROPERTIES:
   :ID:       91886710-5c95-4a49-8155-f7c8ed7e8c9b
   :END:

Toute la journée : 20 avenue de Ségur / SALLE 4.724

** Bootcamp - Mardi 6 février (au LLL)
   :PROPERTIES:
   :ID:       cc90bd05-a707-436d-a854-c6d76fc33334
   :END:

Toute la journée : Liberté Living Lab, 9 rue d'Alexandrie.

** Bootcamp - Mercredi 7 février (à la DINSIC puis à la CNIL)
   :PROPERTIES:
   :ID:       9cc3db1d-3f13-4765-b6c8-967211dbb0e7
   :END:

Matin : 20 avenue de Ségur, salle 4.724

Après-midi : CNIL, 3 place de Fontenoy

** Bootcamp - Jeudi 8 février (au LLL puis au BercyLab)
   :PROPERTIES:
   :ID:       9c5f299c-1a2f-4c02-92c8-6d5de9bcf05f
   :END:

Matin : Liberté Living Lab, 9 rue d'Alexandrie.

Après-midi : BercyLab, 139 rue de Bercy.

** Bootcamp - Vendredi 9 février (SENUM, SGPI, Cour des comptes)
   :PROPERTIES:
   :ID:       950cb905-081e-42e5-84da-97d18f5e47ba
   :END:

Matin : Secrétariat d’État au Numérique, 35 rue Saint Dominique.

Matin : 32 rue de Babylone, à l’Hôtel du [[http://www.gouvernement.fr/secretariat-general-pour-l-investissement-sgpi][Secrétariat général pour
l'investissement]].

Après-midi : 13 rue Cambon, Cour des Comptes.

