Vous pouvez vous abonner à cet agenda public [[https://cloud.eig-forever.org/index.php/apps/calendar/p/5S4DP594PDIVTARU/EIG2018][en ligne]].

* Délégation Ukrainienne rencontre Étalab
  SCHEDULED: <2018-03-27 mar. 16:00>
  :PROPERTIES:
  :ID:       520141c8-7966-4fbd-9883-52900311a167
  :END:

Une délégation Ukrainienne rencontre Etalab, et le programme EIG sera
présenté.

* Mathilde présente EIG en 180 secondes
  SCHEDULED: <2018-03-16 ven. 18:30>
  :PROPERTIES:
  :ID:       4e42ce23-6711-4287-9ad0-0259a4638796
  :END:

Mathilde présente le programme EIG en 180 secondes à un événement sur
« la fonction publique au 21ème siècle », à Superpublic (4 rue de la
Vacquerie, Paris 11ème).

https://www.facebook.com/events/187459725190296/

* Session d’accompagnement EIG - UI/UX et code review
  SCHEDULED: <2018-03-22 jeu. 14:00-18:30>
  :PROPERTIES:
  :ID:       67990e84-36f2-4d92-b5bd-2eb3996a83c9
  :END:
* Session de revue de code avec Quentin
  SCHEDULED: <2018-03-14 mer. 15:00-18:30>
  :PROPERTIES:
  :ID:       fbde68e2-3e66-4702-8350-1e587228bbf9
  :END:

Nous ferons un focus sur le web scraping en plongeant dans les
problématiques et le code d’[[http://github.com/entrepreneur-interet-general/OpenScraper][OpenScraper]] puis nous ferons un autre
focus sur la problématique du nettoyage de données (en python
principalement) en partant du [[https://github.com/entrepreneur-interet-general/predisauvetage][code de Prédisauvetage]].
 
* COMMENT Clinique hebdomadaire sur slack
  SCHEDULED: <2018-03-19 lun. 11:30-12:30 +1w>
  :PROPERTIES:
  :ID:       9695425a-0c77-49b3-be3f-59aadffca168
  :LAST_REPEAT: [2018-03-10 sam. 03:16]
  :END:
  :LOGBOOK:
  - State "CANCELED"   [2018-03-10 sam. 03:16]
  - State "CANCELED"   [2018-03-05 lun. 11:21]
  - State "CANCELED"   [2018-02-23 ven. 14:50]
  - State "CANCELED"   [2018-02-19 lun. 14:20]
  :END:
* Stand up hebdomadaire sur slack
  SCHEDULED: <2018-03-16 ven. 11:30-12:30 +1w>
  :PROPERTIES:
  :ID:       66046c0c-ce90-4ceb-ab33-612cb7f622e9
  :LAST_REPEAT: [2018-03-09 ven. 13:56]
  :END:
  :LOGBOOK:
  - State "DONE"       [2018-03-09 ven. 13:56]
  - State "DONE"       [2018-03-02 ven. 17:06]
  - State "DONE"       [2018-02-23 ven. 12:25]
  - State "DONE"       [2018-02-16 ven. 12:34]
  :END:
* Configuration
  :PROPERTIES:
  :ID:       8c953a43-80c3-40f4-9536-3c95d86992ec
  :END:

#+SEQ_TODO:  STRT(s) NEXT(n) TODO(t) WAIT(w) | DONE(d) CANCELED(c)
#+LANGUAGE:  fr
#+DRAWERS:   HIDE LOGBOOK
#+ARCHIVE:   ~/.eig2/archives/eig-agenda-archives.org::
#+CATEGORY:  EIG
